### ISSUE TITLE
Don't panic on network failure

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-supply-chain#11]
Currently `cargo supply-chain` panics if an API call fails because of this `.unwrap()`:

https://github.com/rust-secure-code/cargo-supply-chain/blob/c960bff32e41827a5116922e9f9aa1d2c7abe2b6/src/publishers.rs#L94-L101

We should retry the request a few times instead of panicking.

**Comment by dutt** [comment]
Took a crack at this.

**Comment by Shnatsel** [comment]
Done in #27, requests are now retried with exponential backoff.
