### ISSUE TITLE
Cache of crates.io data dumps should expire

### ISSUE THREAD

**Issue by HeroicKatora** [rust-secure-code/cargo-supply-chain#13]
Currently, all commands consider any data retrieved via `cargo supply-chain update` as valid.

This might silently leave you with very outdated data (#9 would provide a partial fix).

The usage should either be opt-in with an argument (`--cached`) or there should be some expiration policy. For example, we could consider the dumps outdated if they are older than one day and provide arguments to adjust this such that a duration of `0` ensures that no cache is used.

**Comment by Shnatsel** [comment]
Done in #14
