### ISSUE TITLE
What does `cargo supply-chain update` do?

### ISSUE THREAD

**Issue by jyn514** [rust-secure-code/cargo-supply-chain#21]
On my machine it hangs indefinitely without a progress bar. Presumably this isn't the intended behavior.

**Comment by jyn514** [comment]
Oh I see, it's documented in the readme. It would nice to also put it in `--help` or `-h`. Currently both of those give an error.

**Comment by jyn514** [comment]
It would also be nice to have a progress bar.

**Comment by HeroicKatora** [comment]
> On my machine it hangs indefinitely without a progress bar. Presumably this isn't the intended behavior.

Do you have some timing data for this? It downloads a whole data dump (~250Mb) so that could just be a missing progress bar.

**Comment by jyn514** [comment]
Ok yeah, the issue was a missing progress bar. It finishes after about 30 seconds.
