### ISSUE TITLE
Authors are duplicated if the registry differs

### ISSUE THREAD

**Issue by jyn514** [rust-secure-code/cargo-supply-chain#24]
```
$ cargo supply-chain authors
Alex Crichton <alex@alexcrichton.com>		local
Alex Crichton <alex@alexcrichton.com>		unknown registry
Guillaume Gomez <guillaume1.gomez@gmail.com>		local
Guillaume Gomez <guillaume1.gomez@gmail.com>		unknown registry
Manish Goregaokar <manishsmail@gmail.com>		local
Manish Goregaokar <manishsmail@gmail.com>		unknown registry
```
It might also be nice to deduplicate by the author name, but that's more risky since you don't actually know the same name is the same person. Deduplicating by email would be nice though:

```
Nicholas Cameron <ncameron@mozilla.com>		local
Nick Cameron <ncameron@mozilla.com>		local
Nick Cameron <ncameron@mozilla.com>		unknown registry
```

**Comment by Shnatsel** [comment]
I'd actually call it a feature. These are two different package sources after all, and it's important to highlight all the different accounts of those people that you have to trust (e.g. in several different package registries).
