### ISSUE TITLE
Add progress indication to `update` subcommand

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-supply-chain#28]
`cargo supply-chain update` currently shows no output, and just does its job silently. This is bad for a couple of reasons:

1. There is no indication that a lot of data is going to be downloaded (~250Mb as of right now, and growing). This may be unexpected and undesirable for people using mobile internet connections.
2. On slow connections it's not apparent if any progress is happening or the program just hung.

We need to provide some sort of progress indication, e.g. the amount of data downloaded so far. We cannot show a real progressbar because it would require knowing the size in advance, as well as introducing complex dependencies.

It would also be nice to show some sort of warning that a lot of data may be downloaded.

**Comment by HeroicKatora** [comment]
As a side note: Not all of those 250Mb are being stored, the local data is roughly 10Mb right now. A lot of it is unecessary and discarded but the way that data dumps are offered (`tar.gz`) makes it impossible to seek to only those files that are actually relevant.

**Comment by jyn514** [comment]
~~just use https://github.com/Nemo157/oubliette/~~

**Comment by Shnatsel** [comment]
@Nemo157 Who the Vehk puts Unicode characters into the name of their main git branch?!

**Comment by Nemo157** [comment]
Someone trying to force better support for remote `HEAD` ecosystem wide 😉

**Comment by dutt** [comment]
Looking over the ureq library I think we'll have to switch http library if we want to support partial gets and some kind of progress indicators. Seems the blocking-and-get-everything call() is the only method to get a Response from a Request, unless I'm missing something.

**Comment by Nemo157** [comment]
`Request::call` should only block until the headers are complete, you can then use `Response::into_reader` to stream the data out, updating a progress bar as the data is read (IIRC `indicatif` has support for updating the progress bar status directly from the IO source).

**Comment by dutt** [comment]
Aha, alright then.
