### ISSUE TITLE
Help shows commands misaligned

### ISSUE THREAD

**Issue by Nemo157** [rust-secure-code/cargo-supply-chain#46]
![image](https://user-images.githubusercontent.com/81079/109033996-75b07480-76c7-11eb-9e96-b802e4c475d8.png)

Using tabs for alignment is wrong, they should only be used for initial indentation, since you don't know where the users tab stops will be.

**Comment by Shnatsel** [comment]
Thanks for the report!

I was under the impression that this is how most tools with subcommands handled help text. Are you aware of a better way? Say, spaces, non-breaking spaces, or something else entirely from the dark corners of ascii?

**Comment by Nemo157** [comment]
Afaik generally tools just use spaces, e.g. `clap` use [`fn spaces`](https://github.com/clap-rs/clap/blob/d92592a63b532b7871e7a02bfb9ea4c71f269581/src/output/help.rs#L162-L164) for dynamically calculated widths and a hardcoded [`TAB` made of spaces](https://github.com/clap-rs/clap/blob/d92592a63b532b7871e7a02bfb9ea4c71f269581/src/output/help.rs#L31) for static widths.

**Comment by Shnatsel** [comment]
Fixed in 7b0720df9341e37e40a65ee4517bf1c5df27ce4d. Ripgrep doesn't show any other tabs in the codebase.
