### ISSUE TITLE
Nit re error message

### ISSUE THREAD

**Issue by smoelius** [rust-secure-code/cargo-supply-chain#99]
https://github.com/rust-secure-code/cargo-supply-chain/blob/ede428b811170eae5c7d093d06e371e7d02229fa/src/subcommands/update.rs#L15
The above error message displays as:
```
Error: Downloaded latest daily data dump.
  Warning: it matches the previous version that was considered outdated.
```
"Downloaded latest daily data dump" sounds like the operation succedded, which is unintuitive considering it appears after "Error".

Perhaps something the like the following would better convey the message?
```
Error: Latest daily data dump matches the previous version, which was considered outdated.
```

**Comment by Shnatsel** [comment]
Good catch! Yes, it needs to be more clear. I'd appreciate a PR with this change.
